# Generated by Django 4.1 on 2022-08-16 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiat', models.CharField(max_length=5)),
                ('asset', models.CharField(max_length=5)),
                ('payment_method', models.CharField(max_length=20)),
                ('price_sell', models.FloatField()),
                ('price_buy', models.FloatField()),
                ('date_refresh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arbitration.date')),
            ],
        ),
    ]
