# Generated by Django 4.1 on 2022-08-22 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbitration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='tg_link',
            field=models.CharField(default=1111, max_length=100),
            preserve_default=False,
        ),
    ]
