# Generated by Django 4.1 on 2022-08-17 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbitration', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_registration',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ip_address',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
