# Generated by Django 4.1 on 2022-08-18 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbitration', '0003_user_date_registration_user_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_paid_subscription',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='sub_time_begin',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='sub_time_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='sub_time_end',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
