# Generated by Django 4.1 on 2022-08-18 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbitration', '0004_user_is_paid_subscription_user_sub_time_begin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sub_time_begin',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='sub_time_end',
            field=models.DateTimeField(),
        ),
    ]
