# Generated by Django 4.1 on 2022-08-18 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbitration', '0006_alter_user_sub_time_begin_alter_user_sub_time_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sub_time_begin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='sub_time_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
