# Generated by Django 4.1 on 2022-08-18 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbitration', '0007_alter_user_sub_time_begin_alter_user_sub_time_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hash',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
