# Generated by Django 4.1 on 2022-08-22 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arbitration', '0008_user_hash'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='MyUser',
        ),
    ]
